[package]
name = "transaction-factory"
version = "0.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
cli = { package = "substrate-cli", path = "../../core/cli" }
client = { package = "substrate-client", path = "../../core/client" }
consensus_common = { package = "substrate-consensus-common", path = "../../core/consensus/common" }
indices = { package = "srml-indices", path = "../../srml/indices" }
log = "0.4"
node-runtime = { path = "../../node/runtime" }
node-primitives = { path = "../../node/primitives" }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
primitives = { package = "substrate-primitives", path = "../../core/primitives", default-features = false }
sr-io = { path = "../../core/sr-io" }
sr_primitives = { package = "sr-primitives", path = "../../core/sr-primitives", default-features = false }
srml_support = { package = "srml-support", path = "../../srml/support" }
substrate-service = { path = "../../core/service" }

[dev-dependencies]
substrate-serializer = { path = "../../core/serializer" }
pretty_assertions = "0.5"

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"primitives/std",
]
